version: '3.8'

services:
  app:
    build: .
    ports:
      - "3010:3010"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=3010
      - MONGO_URI=mongodb://mongo:27017/kittydelivery
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
