version: '3.8'

services:
  mc_restaurant:
    build: .
    ports:
      - "3011:3011"
    environment:
      - JWT_SECRET=cestpourlasciencemerciderestercourtoi
      - REFRESH_TOKEN_SECRET=jesensquelesemmerdesvontcommenceraveccettehistoirederefreshtokentoutcapoursetaperundauprojet
      - PORT=3011
      - DB_NAME=kittydelivery
      - DB_ID_NAME=postgres
      - DB_ID_PASSWORD=admin
      - DB_HOST=postgres
      - DB_DIALECT=postgres
    networks:
      - shared-net

networks:
  shared-net:
    external: true
