version: '3.8'

services:
  mc_restaurant:
    container_name: mc_restaurant_0
    build: .
    ports:
      - "4010:4000"
    environment:
      - PORT=4000
      - DB_NAME=kittydelivery
      - DB_ID_NAME=postgres
      - DB_ID_PASSWORD=admin
      - DB_HOST=postgres
      - DB_DIALECT=postgres
    networks:
      - shared-net

networks:
  shared-net:
    external: true
